[package]
name = "rimuru-image-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
image = "0.24.7"
reqwest = { version = "0.11.20", features = ["json", "blocking"] }
select = "0.6.0"
tokio = "1.32.0"
